name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v0.1.0)'
        required: true
      draft:
        description: 'Create as a draft release'
        required: false
        default: 'false'
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          release_name: ${{ github.event.inputs.tag || github.ref_name }}
          draft: ${{ github.event.inputs.draft || 'false' }}
          generate_release_notes: true

